### ISSUE TITLE
'no u' detection is overzealous

### ISSUE THREAD

**Issue by NaCl10** [NaCl10/noubot#5]
The bot is EXTREMELY sensitive to 'no u' and will trigger a LOT of false positives. This has been a known issue for that last *two releases*. This is at least somewhat necessary to prevent false negatives/workarounds/exploits and keep the regex simple.

My proposal is to change the regex in some way so that it will match the area in between 'no' (or any of its alternatives) and 'u' (or any of its alternatives) NO MATTER WHAT, UNLESS there are more than ten NON-whitespace characters. This is something I'm currently working on with help from a friend of mine, but we're having trouble coming up with a regex that works.

[Here's the regex on a nice little explainer website.](https://regex101.com/r/cE7DnX/3/)

**Comment by ClayXrex** [comment]
> it will match the area in between 'no' (or any of its alternatives) and 'u' (or any of its alternatives) NO MATTER WHAT, UNLESS there are more than ten NON-whitespace characters.

Wouldn't that lead to the regex being overzealous? 
Following those rules it would catch the word "nodule" since it does not care what is in between the "no" and the "u" and there are not more than ten non-whitespaces chars in the middle.

Since you check for different spellings of "no u" "hiding" it inside of other characters should not be an issue right?

In case you still want to keep that rule there should still be a max number of characters in between "no" and "u".

I'd propose to check for "no" (or any of its alternatives) and "u" (or any of its alternatives) with a set limit of allowed whitespace/newlines are inbetween.
One could then add certain chars like *, + or - to the check for whitespace/newlines since it would be unlikely that that sequence of chars would make up a real word.

**Comment by ClayXrex** [comment]
I've opened a pr with my proposed check but I seem to be unable to link it to this issue.

**Comment by NaCl10** [comment]
As mentioned in my PR comment (#8), this is a good solution; much better than mine. Thanks a tonne!

I'm not sure why it won't let you link the PR, but oh well.

Closing this issue as it's been resolved thanks to ClayXrex's work in the aforementioned PR #8.
